version: "3"

services:
  medium-api-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=medium
      - POSTGRESQL_PASSWORD=medium
      - POSTGRESQL_DATABASE=medium
  medium-api-pgadmin:
    image: dpage/pgadmin4
    ports:
      - 82:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=medium@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=medium
